name: biz-manage-pro
services:
- name: frontend
  github:
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xs
  routes:
    - path: /

- name: backend
  github:
    branch: main
    deploy_on_push: true
  dockerfile_path: ../backend/Dockerfile
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xs
  envs:
    - key: DATABASE_URL
      scope: RUN_TIME
      value: ${db.DATABASE_URL}
    - key: REDIS_URL
      scope: RUN_TIME
      value: ${redis.REDIS_URL}

databases:
- engine: PG
  name: db
  production: false
  version: "15"

- engine: REDIS
  name: redis
  production: false
  version: "7" 