import type { UserPermissions } from '../types/auth';

export const rolePermissions: Record<string, UserPermissions> = {
  business_owner: {
    canViewDashboard: true,
    canViewSales: true,
    canViewInventory: true,
    canViewCustomers: true,
    canViewSuppliers: true,
    canViewEmployees: true,
    canViewReports: true,
    canManageSettings: true,
    canManageUsers: true,
    canManageProducts: true,
    canManageOrders: true,
    canManagePayments: true,
    canManageInventory: true,
  },
  super_admin: {
    canViewDashboard: true,
    canViewSales: true,
    canViewInventory: true,
    canViewCustomers: true,
    canViewSuppliers: true,
    canViewEmployees: true,
    canViewReports: true,
    canManageSettings: true,
    canManageUsers: true,
    canManageProducts: true,
    canManageOrders: true,
    canManagePayments: true,
    canManageInventory: true,
  },
  customer: {
    canViewDashboard: true,
    canViewSales: false,
    canViewInventory: true,
    canViewCustomers: false,
    canViewSuppliers: false,
    canViewEmployees: false,
    canViewReports: false,
    canManageSettings: false,
    canManageUsers: false,
    canManageProducts: false,
    canManageOrders: true,
    canManagePayments: true,
    canManageInventory: false,
  },
  supplier: {
    canViewDashboard: true,
    canViewSales: false,
    canViewInventory: true,
    canViewCustomers: false,
    canViewSuppliers: false,
    canViewEmployees: false,
    canViewReports: true,
    canManageSettings: false,
    canManageUsers: false,
    canManageProducts: true,
    canManageOrders: true,
    canManagePayments: true,
    canManageInventory: false,
  },
  employee: {
    canViewDashboard: true,
    canViewSales: true,
    canViewInventory: true,
    canViewCustomers: true,
    canViewSuppliers: true,
    canViewEmployees: false,
    canViewReports: true,
    canManageSettings: false,
    canManageUsers: false,
    canManageProducts: true,
    canManageOrders: true,
    canManagePayments: true,
    canManageInventory: false,
  },
  admin: {
    canViewDashboard: true,
    canViewSales: true,
    canViewInventory: true,
    canViewCustomers: true,
    canViewSuppliers: true,
    canViewEmployees: true,
    canViewReports: true,
    canManageSettings: true,
    canManageUsers: true,
    canManageProducts: true,
    canManageOrders: true,
    canManagePayments: true,
    canManageInventory: true,
  },
  manager: {
    canViewDashboard: true,
    canViewSales: true,
    canViewInventory: true,
    canViewCustomers: true,
    canViewSuppliers: true,
    canViewEmployees: false,
    canViewReports: true,
    canManageSettings: false,
    canManageUsers: false,
    canManageProducts: true,
    canManageOrders: true,
    canManagePayments: true,
    canManageInventory: true,
  },
}; 