name: npm audit

on:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit

      - name: Run npm audit fix
        if: failure()
        run: npm audit fix

      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'chore: update dependencies'
          body: 'Automated dependency update'
          branch: 'deps/audit-fix'
          commit-message: 'chore: update dependencies'
          committer: 'GitHub <noreply@github.com>'
          author: 'GitHub <noreply@github.com>'
          labels: 'dependencies,security'
          token: ${{ secrets.GITHUB_TOKEN }} 