name: CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Update deployment
      run: |
        doctl apps update ${{ secrets.APP_ID }} \
          --spec .do/app.yaml

    - name: Wait for deployment
      run: |
        while true; do
          STATUS=$(doctl apps get ${{ secrets.APP_ID }} --format Status --no-header)
          if [ "$STATUS" = "ACTIVE" ]; then
            break
          fi
          sleep 10
        done 